### ISSUE TITLE
f package web page broken link for package guildlines

### ISSUE THREAD

**Issue by harrypower** [GeraldWodni/theforth.net#11]
https://theforth.net/package/f

On the above page there is a link close to the bottom of the page that references this page https://theforth.net/package/f/current-view/guidelines called package-guidelines .  
That link does not work!
I think the link should be as follows http://theforth.net/guidelines

**Comment by GeraldWodni** [comment]
@harrypower Thanks for pointing that out!. It also messed up the link in the github-repository. Fixed in https://github.com/GeraldWodni/f/commit/800d64a5f6a938c07595eb45258d81e6471371e9
