### ISSUE TITLE
new account Email confirmation message maybe not being sent out 

### ISSUE THREAD

**Issue by Budsy** [GeraldWodni/theforth.net#13]
Hmm... I opened a new account registration but never got the confirmation code message. Is it working ok?

Bob

**Comment by GeraldWodni** [comment]
@Budsy Oh my, I fixed the Email server right after I received your issue notification. However, I completely forgot to answer you, sorry! Please try again if you have not.

I also reconfigured the system to relay error messages so I debugging is far easier now.

**Comment by Budsy** [comment]
Gerald,

 

Thanks! I did manage later to get accounts set up on both theforth.net and forth-standard.org .

 

Bob

**Comment by GeraldWodni** [comment]
> Thanks! I did manage later to get accounts set up on both theforth.net and forth-standard.org .

Of course you did, just rememberd finding your nice [base-64](https://theforth.net/package/base64/current-view/base64.f) implementation recently ;)

Well then hopefully nobody else stumbles upon this problem, I'll close this issue, thanks again for reporting!
