### ISSUE TITLE
Table locking issues aft package update

### ISSUE THREAD

**Issue by uho** [GeraldWodni/theforth.net#14]
After updating the package interpretive theForth.net did not acknowledge the upload.

Refreshing the profile now returns

> ER_TABLE_NOT_LOCKED: Table 'users' was not locked with LOCK TABLES

**Comment by GeraldWodni** [comment]
As mentioned offline I thought this issue was just a hickup, but I will have to reimplement the git portion of upload.

Thanks for letting me know!

**Comment by GeraldWodni** [comment]
**Table Locks fixed**
using GET_LOCK and RELEASE_LOCK instead of (UN-)LOCK TABLES

**Packages git repository fixes**
node-git replaces by simple-git; upload works again.

Commit: 1f808eb06dd3e3fad95e33746afa3570b8b3164b
