### ISSUE TITLE
Error 500 in package browser

### ISSUE THREAD

**Issue by ruv** [GeraldWodni/theforth.net#15]
Example URL: http://theforth.net/package/f
The error message on the webpage:
```
ER_TABLE_NOT_LOCKED: Table 'dependencies' was not locked with LOCK TABLES
````

**Comment by RogerLevy** [comment]
Came here to report the same thing.

**Comment by gerryjackson** [comment]
Me  too. It's either a coincidence or my fault as it happened after I uploaded a package. It took a long time and eventually displayed a blank screen implying it had been uploaded. Later it was in the list of packages but selecting it, or any other package displayed the error reported.

**Comment by ghost** [comment]
Can confirm. It happens also if I try to several package directories. Never mind if I came over 'packages' or 'tags'

**Comment by GeraldWodni** [comment]
Thanks for reporting, sorry I overlooked this issue in the notification noise!

I have to change the way the upload interacts with git, until then this issue can arise on a package upload. Please let me know again when you see this in the meantime. See Issue #14 for further discussion.
