### ISSUE TITLE
bug: fget: http error 308

### ISSUE THREAD

**Issue by lolbinarycat** [GeraldWodni/theforth.net#17]
whenever I try to use `fget`, I get this:
```
HTTP-Error: 308
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx/1.17.10</center>
</body>
</html>
```

Anyone know what's up with this?

**Comment by GeraldWodni** [comment]
`fget` uses `HTTP`, my first guess is that I went a bit overzealous forcing all `HTTP` to upgrade to `HTTPS`.

I'll look into it, api requests should be allowed with both protocols.

**Comment by GeraldWodni** [comment]
Forced redirect is disabled, `fget` working again.

@lolbinarycat  Thanks for reporting!
