### ISSUE TITLE
use environment? to test for gforth

### ISSUE THREAD

**Issue by lolbinarycat** [GeraldWodni/theforth.net#18]
use this to conditionally include compat-gforth.4th:
```forth
S" gforth" environment? [IF] 2drop ( ... ) [THEN]
```

**Comment by GeraldWodni** [comment]
`environment?` would indeed be a valid mechanism. However over the last decade it fell out of favor and was replaced by `[DEFINED]` and friends.

I believe you cannot even use it to test for Forth-2012 compliance (I could be wrong about that, so please see for yourself).

If you want to discuss the usage of `environment?` and make a case for it, may I redirect you to [the Forth Standard](https://forth-standard.org/standard/core/ENVIRONMENTq).
