### ISSUE TITLE
improvement: zip download name and contained directory

### ISSUE THREAD

**Issue by uho** [GeraldWodni/theforth.net#3]
# zip download name and contained directory

When downloading a package as zip-file it is currenty
names `<package-name>-current.zip`. In the zip-files it contains all files of the package in a directory named `<version>`, e.g.  1.0.3 .

Proposal: name the zip-file and the directory the same: 

```
<package-name>-<version>.zip and <package-name><version>
```

respectively.

**Comment by GeraldWodni** [comment]
Good Idea, implemented as suggested. This will also allow to extract all downloaded packages in the same directory without collisions.
