### ISSUE TITLE
Is there an API to get a list of packages?

### ISSUE THREAD

**Issue by larsbrinkhoff** [GeraldWodni/theforth.net#7]
Is there an API to the package manager?  (The cool kids use REST, possibly JSON.)

In particular, a way to get a list of all packages?

See librariesio/support#50.

**Comment by GeraldWodni** [comment]
There is now!
Actually I am working on a client for theForthNet right now, so there is more API to come. In the meantime I started with a list of all packages, which gives you a REST-JSON as requested ;)
http://theforth.net/api

**Comment by larsbrinkhoff** [comment]
Great, thanks!

Suggestion for package.4th: add an optional `repository` key.
