### ISSUE TITLE
Unknown file type: 4th

### ISSUE THREAD

**Issue by larsbrinkhoff** [GeraldWodni/theforth.net#8]
Clicking a `.4th` file in a package results in the message `Unknown file type, use raw-view`.

Example: http://theforth.net/package/nige-zapper/current-view/zapper.4th

**Comment by GeraldWodni** [comment]
@larsbrinkhoff  fixed, thanks for reporting ;)

**Comment by larsbrinkhoff** [comment]
Thanks!

Other more-or-less popular Forth file extensions include `.4`, `.f`, `.forth`, `.fr`, `.frt`, and `.ft`.
